import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const packageJsonPath = fileURLToPath(new URL("../package.json", import.meta.url));
const versionSourcePath = fileURLToPath(new URL("../src/version.ts", import.meta.url));
const manifest = JSON.parse(await readFile(packageJsonPath, "utf8"));

if (
  typeof manifest.version !== "string" ||
  !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(
    manifest.version,
  )
) {
  throw new Error(`package.json contains an invalid version: ${String(manifest.version)}`);
}

const source = `/**
 * Package version, used in the default \`User-Agent\`.
 *
 * Inlined rather than read from \`package.json\` at runtime: the SDK must not depend on \`fs\` or on
 * import attributes, so that it loads unchanged in browsers, Cloudflare Workers, and Deno.
 *
 * Generated by \`scripts/sync-version.mjs\` before each build. Do not edit the value by hand.
 */
export const VERSION = ${JSON.stringify(manifest.version)};
`;

await writeFile(versionSourcePath, source, "utf8");
console.log(`Synced SDK VERSION to ${manifest.version}`);
